### ISSUE TITLE
Loading/installing the file

### ISSUE THREAD

**Issue by nrigheriu** [evanplaice/jquery-csv#104]
I cannot load and use this library. I tried inserting, like you mentioned
<script src="jquery-csv.js"></script>
in my local html file. However, as I intuited it did not load. I also tried linking the source to the raw jquery.csv file from github and it failed loading as well. Browser response: 
Loading failed for the <script> with source “https://raw.githubusercontent.com/evanplaice/jquery-csv/master/src/jquery.csv.min.js”.
 I'm sorry for posting this possible foolish question here, but I'm still not that advanced regarding web-development and these kind of "instructions" where many things are assumed of the user are just so annoying and time consuming.

**Comment by evanplaice** [comment]
Is jquery-csv in the same directory as the html file loading it. If not you need to add the correct file path.  Not sure why the raw link isn't workimg but you shouldn't use that anyway. Every release gets automatically pulled and hosted on CDNJS. Just click on the CDNJS badge at the top of the README to goto the page with CDN links.

**Comment by evanplaice** [comment]
Here's the CDN.js link https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.8.9/jquery.csv.min.js
