### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by derek-jackson** [evanplaice/jquery-csv#105]
Hi Evan, this looks really promising, but I'm struggling to understand how to use the script.

I'll always be using the same CSV file, so no need for a file input dialogue. I've tried editing some of your example code, but can't get the page to output anything from the file. I've run the same CSV file through your demo page, and that happily works, so the error is in my code somewhere...

This is my code:
```
<head>
		<script src="http://code.jquery.com/jquery-1.8.2.js"></script>
  		<script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
		<script src="src/jquery.csv.js"></script>
</head>
<body>
<output id="list"></output>
<table id="contents" style="width:100%; height:400px;" border></table>
		
<div id="test_isolate"></div>
		
<script language="JavaScript" type="text/javascript">
		var data = $.csv.toArrays("nnuh_data.csv");
        	var html = '';
        	for(var row in data) {
          		html += '<tr>\r\n';
          		for(var item in data[row]) {
            		html += '<td>' + data[row][item] + '</td>\r\n';
          		}
          		html += '</tr>\r\n';
        	}
        	$('#contents').html(html);
			
		document.getElementById("test_isolate").src = data[2][3];
</script>
</body>
```

Am I missing something obvious? I'm a bit of a noob. Please help!

**Comment by evanplaice** [comment]
The input takes CSV as a string. It doesn't automatically fetch the file. You'll have to do that first by either loading it with a file dialog or fetching it from a server via an AJAX request.

**Comment by derek-jackson** [comment]
Thanks Evan. I'm making a little bespoke web app for a client, so the CSV file probably won't be on a server, but will just sit locally alongside the HTML and script files. Can I not just do it through some sort of simple 'string = contents of file' JS function? Any more advice would be greatly appreciated!

**Comment by evanplaice** [comment]
Yes. That would work too. As long as the input string contains raw csv data, it doesn't matter where the data was sourced from. Loading a file in Node (ex fs.read) is much easier than trying to load it in a browser.
