### ISSUE TITLE
TypeError: csv is undefined

### ISSUE THREAD

**Issue by jonathansekela** [evanplaice/jquery-csv#108]
# Subject of the issue

I love your library and I DEARLY want to use it, but it seems to have a problem loading in Firefox on client side.

## Environment

- Platform: Browser 
- Version: Firefox (up to date as of 2018/04/10)

## Steps to reproduce

- in the html:
`	<script type="text/javascript" src="js/jquery.csv.js"></script>
`
- in the index.js:
`var result = $.csv.toArrays(getTableString("docs/ef-fc-db-stringReadable.csv"));`

## Expected behavior

jquery-csv loads properly, result variable contains the 2-d array from that string

## Actual behaviour

TypeError: csv is undefined - jquery.csv.js:169:9

[Feature]: https://github.com/evanplaice/jquery-csv/issues/new?template=FEAT_TEMPLATE.md&title=feat()&labels=feature
[StackOverflow]: https://stackoverflow.com/questions/tagged/jquery-csv?mixed=1

**Comment by Excel1559** [comment]
Hey Try changing your src to https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.8.9/jquery.csv.js. That worked for me

Ex: `<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.8.9/jquery.csv.js"></script>`

**Comment by jonathansekela** [comment]
@Excel1559 The same error occurs on the same line of cloudflare's js as it does on github's js...I would assume it's a bug on my end, but I checked my code against the [basic usage demo](http://evanplaice.github.io/jquery-csv/examples/basic-usage.html), and it seems to be the exact same thing as what's in the toArrays() function.

**Comment by FatimaJabbar** [comment]
I am facing the following issue

**Comment by nek2712** [comment]
@jonathansekela Hey I was facing the same issue and discovered that it was because the argument passed to $.csv.toArrays() was undefined, check what your <<getTableString("docs/ef-fc-db-stringReadable.csv")>> is returning.

**Comment by jonathansekela** [comment]
@nek2712 It's been so long that I just made my own workaround without this package instead, but now that you mention it that sounds exactly like something I'd do...We'll go with that. Thanks for helping!

**Comment by evanplaice** [comment]
The likely cause is that some library is loaded after jquery-csv that deletes or mutates the $/jQuery namespace

The load order should be:

1. jQuery
2. jquery-csv

Attaching to global namespaces in general is a 'bad' idea and will likely become an anti-pattern of developing JS libraries going forward. This library functioning as an extension of the jQuery namespace is an unfortunate artifact of the time it was originally written.

There are plans to provide to re-implement it as an ES module, completely independent of jQuery once ESM support is fully stable and available in browsers/node.
