### ISSUE TITLE
Not working for a csv file that has 50,000+ records. But it worked fine for 10,000 records. how to increase to size?

### ISSUE THREAD

**Issue by rita5it** [evanplaice/jquery-csv#110]
Hi 

I am readng the data from input CSV files and passing to server.

After selecting the input files, when we click on the Submit button, I am reading the data from this selected CSV input file as below.

Here we are using Jquery CSV toObjects method to read the CSV file data. When the file has 10,000 records (4,400KB) , it is working fine.

Now I am testing for 50,000+ records(25,800KB). It is not working. Developer Tools is crashing in the case of 50,000 + records when i execute the below line of code. It is displaying error as "Something went wrong while displaying this webpage" and displaying the blank page with this error.

**Developer Tools Error is:** 
_Dev Tools was disconnected from the Page.
Once page is reloaded, DevTools will automatically reconnect._

How to increase the size here? Anyone came across this issue? We are using Jquery.csv.js plugin.

This is the code i have.

 `var inputFileData = $.csv.toObjects(importDataFromFiles[0].data)`

Thanks
Rita

**Comment by evanplaice** [comment]
Use [PapaParse](https://www.papaparse.com/). When it comes to processing large amounts of data (ie > 10MB) you're going to exceed the browser's memory limit for Javascript. The only way I know around this limit is to process the CSV as a data stream. PapaParse supports this capability.
