### ISSUE TITLE
Not detect Type of file with different browsers

### ISSUE THREAD

**Issue by juanpineiro** [evanplaice/jquery-csv#112]
I'm developing a plugin that use this jquery plugin to read CSV Plain text files and show the user the information in that file.
All the files were made and save as CSV plain text coma separetad and create/save in OpenOffice.

I found a problem testing the same 2 files in 4 different computers with 3 differents OS.
Computer 1 (with 2 OS correctly installed and working)
- Linux Chrome: read file type OK
- Linux Firefox: read file type OK
- Windows Chrome: read file type "undefined"

Computer 2 (only 1 OS)
- Windows Chrome: read file type "application/vnd.ms-excel" (same file different computer but same browser)

Computer 3 (only 1 OS):
- Apple OS Chrome: read file type empty (string empty with nothing).

**Comment by evanplaice** [comment]
Unfortunately, this is most likely a browser bug (ie lack of support) and not something this library can fix.

While the HTML5 File API has support in many browsers it never officially landed as an official specification so it can't be reliably depended on for full cross-browser support.
