### ISSUE TITLE
'Lint fix' broke code -- can't 'push' to undefined var.

### ISSUE THREAD

**Issue by JohnChambersBestFriend** [evanplaice/jquery-csv#114]
Is this a bug? If not consider asking on [StackOverflow][StackOverflow].

Does the documentation require improvement? Consider posting a [Feature][Feature] with the the recommended changes.

# Subject of the issue
In this PR https://github.com/evanplaice/jquery-csv/commit/e7ecf494fee789b17db9c297c02df206db842a14  line 947 removes initialization of `output`.  At line 949 a push may be attempted on the undefined var which will fail with a JS Runtime.  Recommend reinstating `output = []`.

## Environment

- Platform: Node | Browser 
- Version: Chrome 50
- Usage: Load from file | Load from Ajax | Hooks

## Steps to reproduce

- step1
- step2
- step3

## Expected behaviour

Tell us what should happen

## Actual behaviour

Tell us what happens instead

## References

 - [name](href)

[Feature]: https://github.com/evanplaice/jquery-csv/issues/new?template=FEAT_TEMPLATE.md&title=feat()&labels=feature
[StackOverflow]: https://stackoverflow.com/questions/tagged/jquery-csv?mixed=1

**Comment by evanplaice** [comment]
Fixed in https://github.com/evanplaice/jquery-csv/pull/106
