### ISSUE TITLE
disc()

### ISSUE THREAD

**Issue by daveywb** [evanplaice/jquery-csv#118]
# Is it it possible for the object to use the first column of the headers rather than the first row?

## What Does this Impact?

My csv would be a lot easier to maintain if the headers were 2 rows of data rather than two columns of data

**Comment by evanplaice** [comment]
No. While this lib is very flexible for covering different use cases. Pivoting data from columns into rows is not one of them.

> My csv would be a lot easier to maintain if the headers were 2 rows of data rather than two columns of data

You're right. I can't think of a reasonable explanation why somebody would structure data this way. If the set isn't too big it might be worth importing into Excel, pivoting the columns into headers. Then running it through this lib.
