### ISSUE TITLE
How to trim columns with empty headers

### ISSUE THREAD

**Issue by wolfgangjt** [evanplaice/jquery-csv#119]
The user is uploading a template of an excel doc that they convert to a CSV into my web app and I display it in a data table. The template has some random cells filled out waaaaaaaaaaaaaaaaaaaay out to column cs through cv that have nothing to do with the template. Is there a way to possibly check for an empty header and ignore it? I have no idea how to use the parser.

Thanks

**Comment by evanplaice** [comment]
You can customize the way the parser interprets the data using custom hooks.

Check out this [onParseEntry](https://github.com/evanplaice/jquery-csv/blob/master/docs/hooks-callbacks.md#onparseentry) example.

To summarize, you can inject your own custom parser function that checks the state variable so it knows which column is currently being parsed and returns false if you don't want it included in the output.
