### ISSUE TITLE
Link to basic usage demonstration is broken

### ISSUE THREAD

**Issue by ISOxfordEconomics** [evanplaice/jquery-csv#122]
I am getting a 404 from http://evanplaice.github.io/jquery-csv/examples/basic-usage.html

**Comment by evanplaice** [comment]
Thanks for the heads-up.

Switch to the last version tag and it should work.

The demos are currently undergoing a full redesign so the source is easier for users to follow. The README should be updated within the next few days.

**Comment by evanplaice** [comment]
Scratch that. Choosing a previous tag doesn't work. I just pushed an update that fixes the links. The css styling is broken for some reason but otherwise the demos should work.
