### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by DonBeo** [evanplaice/jquery-csv#148]
Hi,
I think there is a documentation error.  Refer to this stackoverflow question: 

https://stackoverflow.com/questions/65053124/node-js-module-not-found-error-in-node-modules?noredirect=1#comment115008201_65053124

I am new to js so I can not help.

**Comment by lbain** [comment]
I think I had the same problem.

This code works:

```json
// package.json
{
  "dependencies": {
    "jquery-csv": "^1.0.11"
  }
}
```

```js
// main.js
const csv = require('jquery-csv');
console.log(csv.toArrays("title1, title2\n item1, item2"));
```

---

This code doesn't

```json
// package.json
{
  "type": "module",
  "dependencies": {
    "jquery-csv": "^1.0.11"
  }
}
```

```js
// main.js
import * as csv from 'jquery-csv';
console.log(csv.toArrays("title1, title2\n item1, item2"));
```

Error message: `TypeError: csv.toArrays is not a function`

---

I think there's something wrong with the export in `jquery-csv`

**Comment by evanplaice** [comment]
This package isn't ES Module compatible. [@vanillaes/csv](https://github.com/vanillaes/csv) is so that should be used instead on modern codebases.
