### ISSUE TITLE
Options arg not really optional?

### ISSUE THREAD

**Issue by evanplaice** [evanplaice/jquery-csv#48]
_From [joe.falc...@gmail.com](https://code.google.com/u/104369034433446962152/) on February 14, 2015 20:39:25_

What steps will reproduce the problem? 1.Pass a two arg call to $.csv.toObjects(csvData, callback) 2. 3. What is the expected output? What do you see instead? Callback is is not invoked. If an empty object is passed as second arg:

$.csv.toObjects(csvData, {}, callback)

then the callback is invoked. What version of the product are you using? On what operating system? 0.71 Please provide any additional information below. Maybe its just my understanding of optional args .... if both "optional" args need to be present, maybe the docs need amending?

_Original issue: http://code.google.com/p/jquery-csv/issues/detail?id=47_

**Comment by evanplaice** [comment]
_From [evanpla...@gmail.com](https://code.google.com/u/112882755236529658404/) on February 14, 2015 20:49:03_

You're correct.

This issue hasn't come up yet because using jquery-csv in node.js is not the usual use case.

This can most likely be fixed by applying explicit type checking when only 2 arguments are present. I'll look into it.

**Comment by evanplaice** [comment]
_From [joe.falc...@gmail.com](https://code.google.com/u/104369034433446962152/) on February 21, 2015 18:53:18_

It me some time to work out what was going on since it didn't throw any
error.

Might be worth changing the docs if the code can't be fixed in short term.

Joe

**Comment by m-adil** [comment]
any quick fix for [csv.replace not found](https://github.com/evanplaice/jquery-csv/issues/49) error please?

**Comment by coltonehrman** [comment]
Fixed in #128
