### ISSUE TITLE
csv-spectrum test

### ISSUE THREAD

**Issue by maxogden** [evanplaice/jquery-csv#54]
hiya, I just wanted to share a link to https://github.com/maxogden/csv-spectrum, a shared csv test suite. would be awesome if you have any missing cases to submit, or if you wanted to try making jquery-csv pass it

**Comment by evanplaice** [comment]
@maxogden If you take a look at the [test.html.bak.html](https://github.com/evanplaice/jquery-csv/blob/master/test/test.html.bak.html) it contains the tests that guarantee RFC compliance. I started rewriting it as a mocha/chai test runner but was interrupted by work.

There are 7 use cases outlined in RFC 4180 plus an additional 3 amendments that I think should be included in the spec. This was the first of the Javascript CSV libraries to target full RFC compliance and it was built around that goal first. 

Feel free to adapt the tests to your own lib, I would but I'm currently preoccupied with other projects.
