### ISSUE TITLE
Fix fromArrays for multiple delimiters

### ISSUE THREAD

**Issue by janbakker2525** [evanplaice/jquery-csv#57]
When an element for the CSV file contains more than one delimiter only the first delimiter is doubled instead of all delimiters. With delimiter " the element a"b"c becomes a""b"c instead of a""b""c.
line 853 in from Arrays
            strValue = strValue.replace(config.delimiter, config.delimiter + config.delimiter);
might become:
            strValue = strValue.split(config.delimiter).join(config.delimiter + config.delimiter);

**Comment by evanplaice** [comment]
Thanks for the feedback. I'll look into this.

Could you provide a data sample that breaks on this edge case?

The CSV formatter in question was provided by a contributor. At first glance the .split() call should be replaced with a RegEx.replace() call.

**Comment by janbakker2525** [comment]
You're welcome, thanks for the great library. 
I only use the toArray call but when playing around with fromArray I found this.

This is the sample data that breaks it, in CSV it is:
"Boerenjasmijn/Philadelphus ""Snowbelle"""

after CSV import with toArray it becomes:
Boerenjasmijn/Philadelphus "Snowbelle"

When exported to CSV with from Arrays it becomes
"Boerenjasmijn/Philadelphus ""Snowbelle""

This because replace only replaces the " character with "" once instead of as often as possible (twice in this case).

**Comment by javgar66** [comment]
same issue, only fix is to set delimiter to empty

delimiter:""  

I guess is a regexp with no /g option

thanks
