### ISSUE TITLE
can't access jquery.csv.js

### ISSUE THREAD

**Issue by c342xxi** [evanplaice/jquery-csv#59]
For the last 4-5 hours, my script is not able to access the following link.

http://jquery-csv.googlecode.com/git/src/jquery.csv.js

**Comment by ankitg1602** [comment]
Me too getting the same problem

**Comment by Strangeite** [comment]
I was having the same issue but was able to find an old version hosted elsewhere that works.  

https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.71/jquery.csv-0.71.min.js

Obviously, use at your own risk, but I was able to drop this link into my .html code in place of the googlecode link and it now works.  

Obviously, this is a quick and dirty solution.  But I needed my simple program to work right now and find a more permanent solution later.

**Comment by Leechisba** [comment]
https://web.archive.org/web/20160324220311/http://jquery-csv.googlecode.com/git/src/jquery.csv.js

That is the version from a few months ago. I would recommend saving locally.

**Comment by evanplaice** [comment]
Google Code no longer exists.

CDNJS is the preferred alternative. I'll see about updating the CDNJS reference to point to the latest.

Sorry about the inconvenience.

**Comment by evanplaice** [comment]
The examples have been updated to point to the local version of jquery-csv.

If you'd like to serve jquery-csv from a CDN, it is available via CDNJS:
https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.8.3/jquery.csv.min.js
