### ISSUE TITLE
Can not parse a valid csv file

### ISSUE THREAD

**Issue by nicekei** [evanplaice/jquery-csv#61]
Can't parse a valid csv file. 
Failed to parse with "jquery.csv:250 Uncaught Error: CSVDataError: Illegal Quote [Row:5][Col:1]" message
Looks like its a valid file - tested with online CSV Lint(validator) and Google spreadsheet.

(Uploaded the tested data : 
https://dl.dropboxusercontent.com/u/1791448/errorcsv.csv )

**Comment by nicekei** [comment]
Looks like there were some errors while processing the input text.
Forget about it. :)

**Comment by evanplaice** [comment]
Haha. The GIGO struggle is real.

Thanks for taking the time to double-check the input. Saves me from having to chase phantom bugs.
