### ISSUE TITLE
minified version not in 0.8.1

### ISSUE THREAD

**Issue by yitomok** [evanplaice/jquery-csv#62]
I tried to install jquery-csv via bower package, but jquery-csv.min.js is not in the release, should commit c99aa27 included in 0.8.1?

**Comment by evanplaice** [comment]
Yes, guess it's time I automate the release process.

If you need a minified version right away run `grunt uglify` from the project root. If you don't have grunt, it can be installed via `npm install -g grunt-cli`.

I'm drop 0.8.2 and soon and include a minified version. Sorry if this caused any inconvenience.

**Comment by yitomok** [comment]
@evanplaice Can I help on this? I never did this before, perhaps you can give me some info, then I can dig on more myself.

**Comment by evanplaice** [comment]
@yitomok Sure

- fork the repo
- clone your fork
- create the minified version using the directions above
- bump the version number in package.json to 0.8.2
- push the changes to your remove `git push origin master`
- submit a PR on GitHub from your fork to my upstream repo

This is actually a very good intro to contributing on GH

**Comment by evanplaice** [comment]
@yitomok Also, don't hesitate to ask for help if you get stuck.

**Comment by yitomok** [comment]
Hi @evanplaice, I figured out this is a matter of creating new tag, since you already have the minified js. I assume bower will update automatically.

**Comment by evanplaice** [comment]
@yitomok Good point. I didn't realize the master branch already had a minified source.

AFAIK, Bower just points to the latest release and possibly caches it on their own server.

If you're curious about the rest:

NPM is updated directly via the command line using `npm publish`. It requires authentication by the owner so I'm the only one capable of updating the package.

CDN.js needs to be updated still as it's stuck on a really old version. Previously, you'd have to submit a PR with the updated config but they now support pulling from the latest release automatically. I still need to submit an updated config to make it work.

If you have any other questions or would like to help out, don't hesitate to ask.
