### ISSUE TITLE
onPostParse's callback return value has no effect

### ISSUE THREAD

**Issue by jorgeorpinel** [evanplaice/jquery-csv#64]
I have this line somewhere:

``` js
                obectArray = $.csv.toObjects(data, {onPostParse: processData});
```

and elsewhere I have a `function processData(objs)...` which iterates over `objs` and does some filtering. What the function returns HAS NO EFFECT. I can `return []` and still `obectArray` will end up being what `processData` receives: `objs`.

There's a weird element to this. What does have an effect are the modifications I do to `objs` within `processData`, BUT ONLY inside `objs.forEach` callback/loops! If all I did was `objs = []`, similar to returning `[]`, no change. Confused.

No bueno :(

I'm going to have to not use the callback and just process the data after loading I guess.

**Comment by evanplaice** [comment]
Fixed by #124
