### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by ranaictiu** [evanplaice/jquery-csv#65]
Some character is encoding into some unrecognizable char. For example the text "**Code will be approximately between Latitude 5°N and 6°S**" is getting converted to  "**Code will be approximately between Latitude 5�N and 6�S**"

**Comment by sander-v-bergen** [comment]
Were you able to fix this? I have the same issue with multiple specials chars. when I view the output in HTML. Changing HTML encoding doesn't resolve it.. Thanks.

**Comment by evanplaice** [comment]
Jquery-csv doesn't make any attempt to encode HTML characters, it simply returns a string.

It should be possible to create onParseValue hook that properly escapes unicode characters.

For example:
- ° -> \&deg;

I'm going to put this on the backlog for now. If progress toward 0.9 goes well I'll add a documentation spec that shows how to accomplish this.
