### ISSUE TITLE
Converting csv to object and back to csv leads to broken quotes

### ISSUE THREAD

**Issue by garemoko** [evanplaice/jquery-csv#66]
When converting a csv to an object then back to a csv, if any cells have multiple " symbols, only the first quote in each cell is escaped in the output.

Input:

```
1,2
"foo ""1"" bar ","2"
```

Output (expected the same as input):

```
1,2
"foo ""1" bar ",2
```

**Comment by garemoko** [comment]
Looks like the problem is going from object to csv.

**Comment by garemoko** [comment]
And here's the problem line: https://github.com/evanplaice/jquery-csv/blob/master/src/jquery.csv.js#L853

Should be recursive. See http://stackoverflow.com/questions/1144783/replacing-all-occurrences-of-a-string-in-javascript

**Comment by garemoko** [comment]
@evanplaice PR up for you to review sir. Thanks for this project!

**Comment by cactusme** [comment]
any update?

**Comment by garemoko** [comment]
This repo hasn't been updated in nearly a year, I think your best bet is to just use by fork: https://github.com/garemoko/jquery-csv

**Comment by cactusme** [comment]
Thanks @garemoko.  I pull the bits from bower so do you have any suggestions?

**Comment by garemoko** [comment]
Not really. Does it help that it's a really tiny code change? Could you make it manually or would it get overwritten? https://github.com/garemoko/jquery-csv/commit/86ee514f5bed9cda90922485869ab6817f14255e

Otherwise my best idea is don't pull it from bower.
