### ISSUE TITLE
csv.replace is not a function at line 170

### ISSUE THREAD

**Issue by tushardave26** [evanplaice/jquery-csv#69]
Hello Author,

I am trying to use your library in my web application. Unfortunately, I am experiencing an error "csv.replace is not a function at line 170". For your reference I have pasted my code below:

``` app.js
function populateTraitMenu (files) {

    if (window.FileReader) {
        var fileType = files[0].type;
        alert(fileType);
        alert(files[0]);
        if (fileType == "text/plain" || fileType == "text/csv" || fileType == "application/vnd.ms-excel") {
            if (fileType == "text/plain") {
                var dataArray = $.csv.toArrays(file[0], {delimiter : "\t"});
                alert(dataArray[0]);
            } else if (fileType == "text/csv" || fileType == "application/vnd.ms-excel") {
                var dataArray = $.csv.toArrays(files[0], {delimiter : ",", header : true});
                alert(dataArray[0]);
            }
        } else {
            alert("You are trying to upload a file with a type which is not allowed. Currently, we are supporting only CSV (i.e. .csv) and TEXT (i.e. .txt) files.");
        }
    } else {
        alert("FileReader is not supported for your current browser. Please use Google Chrome browser.");
    }
}
```

"populateTraitMenu" is onchange function for inpute type file. Am I doing anything wrong? Or it's a bug?

I hope I am clear enough.

Can you help me to solve the issue?

Thanks.

Best,
Tushar

**Comment by cooperate** [comment]
I'm having this issue running server side
`csv.replace(match, function (m0) {
           ^

TypeError: Cannot read property 'replace' of undefined
    at Object.parse (U:\app\node_modules\jquery\src\jquery.csv.js:170:12)`

**Comment by evanplaice** [comment]
Whatever is getting fed into ` $.csv.toArrays` is not a string. 

Are you sure the files opened correctly. I'll see about adding some error checking to throw an exception if a wrong type is encountered.
