### ISSUE TITLE
csv.toArrays(data) working but last csv input data missing in Array

### ISSUE THREAD

**Issue by Jellest** [evanplaice/jquery-csv#72]
I am successfully able to parse Google sheet data using csv.toArrays(csvd)

The issue is, however, that the very last csv input data of the sheet is always left out in my Array. This data is shown in the published Google Sheet csv file.

Any idea why this might happen?

**Comment by justinwinslow** [comment]
I just noticed this as well. Adding a new line to the string before sending it to `toArrays` fixes it. I haven't looked into why it's happening, though.

**Comment by Jelle002** [comment]
Yes that was my solution as well. Actually, this problem only occurred if the Array existed of only one column of data. When getting 2 or more column through the toArrays , the problem disappears..

**Comment by justinwinslow** [comment]
Interesting. 👍

**Comment by coltonehrman** [comment]
Is there a data sample I can use to test this issue? I tried creating a test Google Sheet document and exported it as csv, but not having the same issue described.
