### ISSUE TITLE
parse multiline csv into arrays with row numbers

### ISSUE THREAD

**Issue by gromitroger** [evanplaice/jquery-csv#83]
I am pretty new to js coding, but I see that jquery can do the parsing of my data arrays, But how to give the array values an index equal to their row numbers?  If my csv file looks like
av, bv, cv
av bv, cv
etc.
and I want to create values row=1, av(1), bv(1), cv(1);  row=2, av(2), bv(2), cv(2);  etc.
can jquery-cv be used somehow to get the arrays as shown?  My intent is to put the list of strings av() into an options list for a form, and then the user selected value of av() will be associated by use of row number with the values bv() and cv().

**Comment by evanplaice** [comment]
This isn't jquery, it's a CSV parser extension pligin for jquery.
