### ISSUE TITLE
Cannot upload the same file again

### ISSUE THREAD

**Issue by rameshkunwar** [evanplaice/jquery-csv#85]
I cannot upload  the same file again. I can see it has 'change' event so when we try to upload the same file, no new event is triggered. However, some times we can update the csv file and try to upload again.

**Comment by evanplaice** [comment]
Is this an issue in the demo? If so, I'll can look into fixing it.

If not, it's likely a HTML5 File API issue. Jquery-csv has no awareness of files or events. It simply consumes CSV and spits out data, or vice versa. How that data gets passed into the parser is generally outside of the scope of this project.
