### ISSUE TITLE
example for reading data from a csv file

### ISSUE THREAD

**Issue by connor11528** [evanplaice/jquery-csv#86]
I have the csv file sitting in my root directory. How do I read the file using javascript and this library? All of the examples already have the csv data in the html

**Comment by evanplaice** [comment]
On what platform. Are you trying to do this from the browser or from Node.js.

**On the client-side**

You need to use the HTML5 File API, which presents the user with a file dialog where they can select the file to load. 

Check out the file-handling demo.

*Or*

Load the file from the server using AJAS ,

Currently there is no Ajax demo, this should be added in the near future.

**On the server-side**

In Node, you need to use a filereader to pull the csv in as a string, then feed that string into the parser so it can be converted to data.

Check out the node-usage demo.
