### ISSUE TITLE
I am having problem in parsing a csv data with /" or /' value

### ISSUE THREAD

**Issue by Sreelakshmigc** [evanplaice/jquery-csv#89]
Hi Evan Plaice,

Great library thank you. 

I am using $.csv.toArrays() and my csv data has /" and /' values, that is escape characters as part of it. This is causing CSVDataError: Illegal State [Row:number][Col:number]. Can you please help me fix this. 

Regards

**Comment by evanplaice** [comment]
Following the CSV spec, / is not a valid escape character. Double up the quotes for escaping (ie "" or "").
