### ISSUE TITLE
Importing issue in React

### ISSUE THREAD

**Issue by dhavaljardosh** [evanplaice/jquery-csv#91]
As I am using React in ES6,
I am unable to import using

```
var $ = jQuery = require('jquery');
require('./jquery.csv.js');
```

Found a way to import using
```import * as randomName from 'jquery-csv'```

Now how am I able to use ```$.csv.toArrays(csv);```/```$.csv.toObjects(csv);```?

**Comment by dhavaljardosh** [comment]
```randomName.toArray(csv);```

This did work, but now I am getting the following error

>```TypeError: csv.replace is not a function```

How to solve this?

**Comment by evanplaice** [comment]
This project uses an IIFE to attach the 'csv' namespace to $.

Try using:

```javascript
var $ = jQuery = require('jquery');
var $.csv  = jQuery.csv = require('./jquery.csv.js');
````

I'm not all that familiar with React yet. What I do know is that libraries that import a big singleton into the global namespace (ie jquery) can cause headaches in System.js/Webpack. If you have jQuery working the above code should also work.

I'm considering building a final 1.0 release of this lib and transitioning the codebase to ES6 and dropping the requirement to use jquery altogether.

The changes require a lot of restructuring and designing a new API. I'm waiting until native ESM support is available in all browsers until I make the transition.
