### ISSUE TITLE
spec(Document ESM Import Usage)

### ISSUE THREAD

**Issue by evanplaice** [evanplaice/jquery-csv#93]
# Document ESM Import Usage

With the introduction of modules in ES6, we have a new and better path to import modules into JS. Jquery-csv should work with this currently but the documentation is lacking a good example for users.

## Goals
- Document the usage
- Provide an useful example that users can use to write their own code

## Milestones
- [x] Update [README.md - Use Cases](https://github.com/evanplaice/jquery-csv#use-cases) to include an `ESM Import` section
- [x] Add a 'esm-usage' example to /examples

## Details

The following code should work to import jquery-csv.
```javascript
import {$,jQuery} from 'jquery';
import {$.csv ,jQuery.csv } from 'jquery-csv';
```

## References

 - readme improvement on nodejs - #68

**Comment by evanplaice** [comment]
Ref #68

**Comment by evanplaice** [comment]
Add a template for submitting new specifications

**Comment by joeLoftus** [comment]
Hello Evan! I am interested in your project and would like to make my first open source contribution to this issue. 

For the 'esm-usage' file, should it be similar to the node-usage.js file where example code is simply shown? Or should it be similar to the .html files where some example is demonstrated. I'm not too sure what an example of importing would ultimately demonstrate in a file similar to the html examples.
