### ISSUE TITLE
spec(Document Date Parsing User Defined Callback)

### ISSUE THREAD

**Issue by evanplaice** [evanplaice/jquery-csv#94]
# Document Date Parsing User Defined Callback

CSV can be a challenging format to work with because it is missing a lot of the metadata features that come with other data formats. One major issue is the lack of types. Some implementations attempt to overcome this obstacle by implementing type inference (ie guess the type based on the value), but this can cause some weird edge cases if the parser guesses the wrong type.

Instead of repeating this mistake, jquery-csv makes no assumptions about the data, and instead, returns all values as strings. Since there are cases where it's preferred to add type inference to the parser, jquery-csv makes it possible to leverage hooks to pass data processing functions into the parser.

One example of this usage already exists in the form of the $.castToScalar() preParse hook. What this specification attempts to address is the addition of another built-in hook that can parse a date value.

## Goals

- Add an example to [Hooks & Callbacks](https://github.com/evanplaice/jquery-csv/blob/master/docs/hooks-callbacks.md)

## Milestones

- [ ] Update [Hooks & Callbacks](https://github.com/evanplaice/jquery-csv/blob/master/docs/hooks-callbacks.md)

## Details

The existing [castToScalar](https://github.com/evanplaice/jquery-csv/blob/master/docs/hooks-callbacks.md#csvhookscasttoscalarvalue) documentation is a good starting point.

The `castToScalar()` [source](https://github.com/evanplaice/jquery-csv/blob/74606914c127150aaae0589b43ccecb598417cb1/src/jquery.csv.js#L59) shows how a user defined hook is implemented.

Because type inference can be expensive, this example will show how to detect a specific column, and apply the transformation to values contained within that column.

The example should demonstrate how to detect and apply the transformation to only the 2nd column of the data.

`onParseValue()` hooks use the following signature.

```javascript
function(value, state) {
  // value contains the string value, this is what the transform will be applied to
  // state contains 2 properties, row, and col. Use col for the example
  // when the transform is done return the result
}
```

## References

 - Parse datetime field to google charts. - [#25](https://github.com/evanplaice/jquery-csv/issues/25)

**Comment by akn95** [comment]
Hello Evan! I am interested in your project and would like to make my first open source contribution to this issue.
I have a question regarding this feature, will there be a specific format of parsed date and if there is then , will it be taken from user or will it be a fixed format decided inside the function.

**Comment by evanplaice** [comment]
Hi Aditya.

There is no strict requirement for which date format to use. This addition would be more of a demonstration of how to parse any custom date format. For simplicity sake, it could just use ISO 8601 (ie common international date format).

Let's say the date is `2019-02-26`

Define an `onParseEntry` function that filters for the correct row using `state.colNum` the `entry` value is fed into `Date.parse` and that value is returned. All other values should just be returned. When you inject a custom parser function, the values it returns are what get inserted into the output data array.

If you have additional questions, feel free to ask.

**Comment by evanplaice** [comment]
Added in #123
